apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: dev
spec:
  containers:
    - name: myapp
      image: luksa/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
